import type { Plugin, ResolvedConfig } from "vite";
import { createFilter } from "vite";
import {
  generateChannelPrefixModule,
  generateChannelsModule,
  generateHandlersLoaderModule,
} from "./plugin/codegen.js";
import { splitFilePatterns } from "./plugin/files.js";
import {
  scanForHandlers,
  transform,
  transformForMain,
} from "./plugin/transform.js";
import type {
  ElectronActionsOptions,
  ElectronActionsPlugins,
} from "./types.js";

// ── Internal virtual module IDs ────────────────────────────────

// Generated by env:"main" — side-effect imports of all "use node" files
const HANDLERS_MAP_ID = "vite-plugin-electron-actions:load-handlers";
const RESOLVED_HANDLERS_MAP_ID = "\0vite-plugin-electron-actions-load-handlers";

// Generated by env:"preload" — exports a channel string array
const CHANNELS_ID = "vite-plugin-electron-actions:channels";
const RESOLVED_CHANNELS_ID = "\0vite-plugin-electron-actions-channels";
const CHANNEL_PREFIX_ID = "vite-plugin-electron-actions:channel-prefix";
const RESOLVED_CHANNEL_PREFIX_ID =
  "\0vite-plugin-electron-actions-channel-prefix";
const DEFAULT_CHANNEL_PREFIX = "$$electron-actions:";

function createFilesFilter(
  files: string[],
  root: string,
): (id: unknown) => boolean {
  const { include, exclude } = splitFilePatterns(files);
  return createFilter(include, exclude, { resolve: root });
}

// ── Plugin ─────────────────────────────────────────────────────

type ElectronActionsEnv = "renderer" | "main" | "preload";

export function electronActions(
  options: ElectronActionsOptions,
): ElectronActionsPlugins {
  return {
    renderer: createElectronActionsPlugin("renderer", options),
    main: createElectronActionsPlugin("main", options),
    preload: createElectronActionsPlugin("preload", options),
  };
}

function createElectronActionsPlugin(
  env: ElectronActionsEnv,
  options: ElectronActionsOptions,
): Plugin {
  const channelPrefix = options.channelPrefix ?? DEFAULT_CHANNEL_PREFIX;
  const files = options.files;

  if (env === "renderer") {
    let root = process.cwd();
    // Recreate this once Vite provides the resolved root.
    let fileFilter = createFilesFilter(files, root);

    return {
      name: "electron-actions:renderer",

      configResolved(config: ResolvedConfig) {
        root = config.root;
        fileFilter = createFilesFilter(files, root);
      },

      transform: {
        handler(code, id) {
          // Skip files outside the configured glob patterns before parsing.
          if (!fileFilter(id)) return null;

          const result = transform(code, id, channelPrefix);
          if (!result) return null;

          return { code: result, map: null };
        },
      },
    };
  }

  if (env === "main") {
    let root = process.cwd();
    // Recreate this once Vite provides the resolved root in `configResolved`.
    let fileFilter = createFilesFilter(files, root);

    return {
      name: "electron-actions:main",

      configResolved(config: ResolvedConfig) {
        root = config.root;
        fileFilter = createFilesFilter(files, root);
      },

      resolveId(id) {
        if (id === HANDLERS_MAP_ID) return RESOLVED_HANDLERS_MAP_ID;
        if (id === CHANNEL_PREFIX_ID) return RESOLVED_CHANNEL_PREFIX_ID;
        return null;
      },

      load(id) {
        if (id === RESOLVED_CHANNEL_PREFIX_ID) {
          return generateChannelPrefixModule(channelPrefix);
        }

        if (id === RESOLVED_HANDLERS_MAP_ID) {
          const registry = scanForHandlers(files, root, channelPrefix);
          return generateHandlersLoaderModule(registry);
        }

        return null;
      },

      transform: {
        handler(code, id) {
          // Skip files outside the configured glob patterns before parsing.
          if (!fileFilter(id)) return null;

          const result = transformForMain(id, code, channelPrefix);
          if (!result) return null;

          return { code: result, map: null };
        },
      },
    };
  }

  if (env === "preload") {
    let root = process.cwd();

    return {
      name: "electron-actions:preload",

      configResolved(config: ResolvedConfig) {
        root = config.root;
      },

      resolveId(id) {
        if (id === CHANNELS_ID) return RESOLVED_CHANNELS_ID;
        if (id === CHANNEL_PREFIX_ID) return RESOLVED_CHANNEL_PREFIX_ID;
        return null;
      },

      load(id) {
        if (id === RESOLVED_CHANNEL_PREFIX_ID) {
          return generateChannelPrefixModule(channelPrefix);
        }

        if (id === RESOLVED_CHANNELS_ID) {
          const registry = scanForHandlers(files, root, channelPrefix);
          return generateChannelsModule(registry);
        }

        return null;
      },
    };
  }

  throw new Error(
    `[vite-plugin-electron-actions] Unknown internal env: "${env}".`,
  );
}

export type {
  ElectronActionsOptions,
  ElectronActionsPlugins,
} from "./types.js";
