import type { Plugin, ResolvedConfig } from "vite";
import { createFilter } from "vite";
import {
  generateChannelsModule,
  generateHandlersLoaderModule,
} from "./plugin/codegen.js";
import {
  scanForHandlers,
  transform,
  transformForMain,
} from "./plugin/transform.js";
import type { ElectronActionsOptions } from "./types.js";

// ── Internal virtual module IDs ────────────────────────────────

// Generated by env:"main" — side-effect imports of all "use node" files
const HANDLERS_MAP_ID = "vite-plugin-electron-actions:load-handlers";
const RESOLVED_HANDLERS_MAP_ID = "\0vite-plugin-electron-actions-load-handlers";

// Generated by env:"preload" — exports a channel string array
const CHANNELS_ID = "vite-plugin-electron-actions:channels";
const RESOLVED_CHANNELS_ID = "\0vite-plugin-electron-actions-channels";

// ── Plugin ─────────────────────────────────────────────────────

export function electronActions(options: ElectronActionsOptions): Plugin {
  // The optional chaining ("options?.env") is to help display a more specific
  // error message if the user forgets to pass an options object
  const env = options?.env;

  if (env === "renderer") {
    const includePattern = options.include ?? /\.[jt]sx?$/;
    const filter = createFilter(includePattern, options.exclude);

    return {
      name: "electron-actions:renderer",

      transform: {
        filter: { id: includePattern },
        handler(code, id) {
          // Guard for Vite < 6.3 where hook filters are not supported.
          if (!filter(id)) return null;

          const result = transform(code, id, options.channelPrefix ?? "");
          if (!result) return null;

          return { code: result, map: null };
        },
      },
    };
  }

  if (env === "main") {
    const includePattern = options.include ?? /\.[jt]sx?$/;
    const filter = createFilter(includePattern, options.exclude);
    const scanDirs = options.scanDirs ?? ["src"];
    const channelPrefix = options.channelPrefix ?? "";
    let root = process.cwd();

    return {
      name: "electron-actions:main",

      configResolved(config: ResolvedConfig) {
        root = config.root;
      },

      resolveId(id) {
        if (id === HANDLERS_MAP_ID) return RESOLVED_HANDLERS_MAP_ID;
        return null;
      },

      load(id) {
        if (id === RESOLVED_HANDLERS_MAP_ID) {
          const registry = scanForHandlers(scanDirs, root, channelPrefix);
          return generateHandlersLoaderModule(registry);
        }

        return null;
      },

      transform: {
        filter: { id: includePattern },
        handler(code, id) {
          // Guard for Vite < 6.3 where hook filters are not supported.
          if (!filter(id)) return null;

          const result = transformForMain(id, code, channelPrefix);
          if (!result) return null;

          return { code: result, map: null };
        },
      },
    };
  }

  if (env === "preload") {
    const scanDirs = options.scanDirs ?? ["src"];
    const channelPrefix = options.channelPrefix ?? "";
    let root = process.cwd();

    return {
      name: "electron-actions:preload",

      configResolved(config: ResolvedConfig) {
        root = config.root;
      },

      resolveId(id) {
        if (id === CHANNELS_ID) return RESOLVED_CHANNELS_ID;
        return null;
      },

      load(id) {
        if (id === RESOLVED_CHANNELS_ID) {
          const registry = scanForHandlers(scanDirs, root, channelPrefix);
          return generateChannelsModule(registry);
        }

        return null;
      },
    };
  }

  throw new Error(
    `[vite-plugin-electron-actions] Unknown env: "${env}". Must be "renderer", "main", or "preload".`,
  );
}

export type { ElectronActionsOptions } from "./types.js";
