// Ambient type declaration for the virtual module generated by the
// electron-actions Vite plugin at build time.
declare module "electron-actions:preload" {
  /**
   * Map of function name → IPC channel string, built at compile time
   * from all `"use node"` handlers discovered in the project.
   *
   * This is consumed by `createElectronActionsRenderer` in the preload
   * script to wire up individual named IPC functions via contextBridge.
   */
  export const channels: Record<string, string>;
}
